### ISSUE TITLE
Not able to instialize DenseStorage.h line 194 Eigen

### ISSUE THREAD

**Issue by abhishek31704** [charalambos/StructurePointcloud#2]
![Capture](https://user-images.githubusercontent.com/13964868/111958293-59003480-8aed-11eb-8341-3543ad096aa6.JPG)
![Capture2](https://user-images.githubusercontent.com/13964868/111958376-73d2a900-8aed-11eb-9f04-f27b97c33085.JPG)

The program crashes in the Dense Storage header file line 194. Not able to find what is the error.

**Comment by abhishek31704** [comment]
I am using CodeBlocks in windows with GNU GCC compiler as MinGW.

**Comment by abhishek31704** [comment]
Okay, now I have setup Ubuntu with GCC and using CodeBlock. Ubuntu compilation is seamless. 

While running the program, I receive segmentation fault in BoundingBox::getMinPt() const () ()

I am passing the text file as an argument in code block.

**Comment by abhishek31704** [comment]
And on the command line, the segmentation fault is after 
Finished Structuring, which is the same issue raised by the other user.

**Comment by charalambos** [comment]
Abhishek,

The first error message has nothing to do with this repo. It's an Eigen library issue. 

Regarding the second issue, as I already showed to the other user, the code works fine on my end and I cannot know what is causing the error on your system. Maybe it's Ubuntu; I am using OpenSUSE again. It may help pinpoint the problem if you look at the intermediate output files. 

Best,

C.

**Comment by abhishek31704** [comment]
Hello Charis,

Thanks, it is working now.
